name: boil_the_ocean
on:
  workflow_dispatch:
jobs:
  boil_the_ocean:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run
        run: |
          source ${{github.workspace}}/boil_the_ocean.sh
